// <auto-generated />
namespace BestMovies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_genre_and_other_samples : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_genre_and_other_samples));
        
        string IMigrationMetadata.Id
        {
            get { return "201804301225082_add_genre_and_other_samples"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
