// <auto-generated />
namespace BestMovies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_genre_sample : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_genre_sample));
        
        string IMigrationMetadata.Id
        {
            get { return "201805021209495_add_genre_sample"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
