// <auto-generated />
namespace BestMovies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sample_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sample_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300956538_sample_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
